M48
; DRILL file {KiCad 8.0.1} date 2025-01-14T19:26:38+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-01-14T19:26:38+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X153.025Y-118.45
T2
X153.025Y-113.95
M30
